#pragma once

typedef enum {
    CBANK_OK = 0,
    CBANK_ERR_NULL,
    CBANK_ERR_EMPTY,
    CBANK_ERR_LENGTH,
    CBANK_ERR_FORMAT,
    CBANK_ERR_DUPLICATE,
    CBANK_ERR_NOT_FOUND,
    CBANK_ERR_FULL,
    CBANK_ERR_BANK_COUNTRY,
    CBANK_ERR_BANK_CODE,
    CBANK_ERR_NAME,
    CBANK_ERR_RESERVE_DIGIT
} CbankResult;